Feature/3000 define companies api
levinineiasi/ppac-service pull request #3
Opened 2023-03-23 10:18 UTC by Madalina-Carausu

Add Companies and Openings APIs.

2023-03-23 10:35 UTC, istRazvan9 requested changes
This application has not yet been deployed in any environment, and I believe that having multiple SQL files for creating tables may not be necessary.

2023-03-23 10:38 UTC, istRazvan9 commented on db/flyway/db-admin-migrations/V1_3__update_companies_table.sql
This application has not yet been deployed in any environment, and I believe that having multiple SQL files for creating tables may not be necessary.

2023-03-23 11:02 UTC, istRazvan9 commented on ppac-service-common/src/main/kotlin/com/levi9/ppac/service/api/repository/CompanyRepository.kt
> +    fun findFirstByOpenings_Id(openingId: UUID): CompanyEntity?
You can use 'findFirstByOpeningsId' instead of 'findFirstByOpenings_Id' . Both methods should achieve the same result. In this way sonar will pass format validation.

2023-03-23 11:02 UTC, istRazvan9 commented on ppac-service-common/src/main/kotlin/com/levi9/ppac/service/api/repository/CompanyRepository.kt
> +    fun findCompanyEntitiesByOpenings_Trainers_Id(trainerId:UUID): List<CompanyEntity>
Same here

2023-03-23 11:10 UTC, istRazvan9 commented on db/flyway/db-admin-migrations/V1_2__create_openings_db.sql
> +    PERIOD_COUNT INTEGER NOT NULL,
You can add constraint : CHECK (PERIOD_COUNT >= 0) to store positive values for this field. Apply this for all INT columns positives.

2023-03-23 12:58 UTC, istRazvan9 commented on ppac-service-common/src/main/kotlin/com/levi9/ppac/service/api/data_classes/CompanyCode.kt
> +import com.levi9.ppac.service.api.domain.OpeningEntity
Remove this unused import

2023-03-23 12:59 UTC, istRazvan9 commented on ppac-service-common/src/main/kotlin/com/levi9/ppac/service/api/repository/OpeningRepository.kt
> +import org.springframework.data.jpa.repository.Query
Remove unused imports

2023-03-23 13:01 UTC, istRazvan9 commented on ppac-service-controller/mvp/src/main/kotlin/com/levi9/ppac/service/api/service/controller/mvp/OpeningsController.kt
> +import com.levi9.ppac.service.api.data_classes.Company
Remove unused import

2023-03-23 13:04 UTC, istRazvan9 commented on ppac-service-impl/src/main/kotlin/com/levi9/ppac/service/api/service/CodeServiceImpl.kt
> +    val openingRepository: OpeningRepository
This val is not used. Remove it

2023-03-23 13:09 UTC, istRazvan9 commented on ppac-service-common/src/main/kotlin/com/levi9/ppac/service/api/data_classes/Company.kt
> +    var openings: List<Opening>? = null
You can use emptyList() instead null

2023-03-23 13:20 UTC, istRazvan9 commented on ppac-service-common/src/main/kotlin/com/levi9/ppac/service/api/domain/CompanyEntity.kt
> +    var openings: List<OpeningEntity> = ArrayList<OpeningEntity>()
You can use "= ArrayList()"

2023-03-23 13:34 UTC, istRazvan9 commented on ppac-service-common/src/main/kotlin/com/levi9/ppac/service/api/domain/TrainerEntity.kt
> +    var linkedinURL: String,
If this field is nullable, I think It might not be necessary to be included in constructor

2023-03-23 13:43 UTC, istRazvan9 commented on ppac-service-impl/src/main/kotlin/com/levi9/ppac/service/api/service/CompanyServiceImpl.kt
> +        if (!codeRepository.isCompanyCode(securityContext.getAccessCode(), id)) {
You can replace "if(!condition){throw ex}" with require(condition){throw ex}" . Apply this for all cases

2023-03-23 14:13 UTC, istRazvan9 commented on ppac-service-impl/src/main/kotlin/com/levi9/ppac/service/api/service/CompanyServiceImpl.kt
> +        val activeOpenings = company.openings?.filter { it.available }
The sign '?' it is not necessary. A warn "Unnecessary safe call on a non-null receiver of type List<OpeningEntity>" is present.  You can resolve this by removing '?' . Do this for all warn cases in this class.

2023-03-23 14:41 UTC, 19stephan93 requested changes
run build on local and fix detekt issues, at least those quick "NewLineAtEndOfFile" issues

2023-03-24 11:16 UTC, 19stephan93 approved these changes

2023-03-27 11:13 UTC, istRazvan9 approved these changes

2023-03-27 13:25 UTC, merged